export const LOCALE_SELECTED= 'LOCALE_SELECTED';

export const PAGE_NO_CHANGED= 'PAGE_NO_CHANGED';

export const MEN_PRODUCTS_RETRIEVAL ='MEN_PRODUCTS_RETRIEVAL';

export const WOMEN_PRODUCTS_RETRIEVAL ='WOMEN_PRODUCTS_RETRIEVAL';

export const CHANGE_RECORDS_PER_PAGE ='CHANGE_RECORDS_PER_PAGE';

export const CHANGE_IMAGE_SOURCE ='CHANGE_IMAGE_SOURCE';

export const ADD_TO_CART ='ADD_TO_CART';

export const CUSTOMER_PURCHASE ='CUSTOMER_PURCHASE'; 